### ISSUE TITLE
Documentation Issue: Disabling HTML5

### ISSUE THREAD

**Issue by bobbykellogg** [ConciseCSS/concisecss.github.io#5]
The example provided for the XHTML 1.0 strict doctype is displaying the one for HTML 4.01 transitional:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
```

It should be:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
```
line 26 of concisecss.github.io/get-started/disabling-html5.html

**Comment by jameskolce** [comment]
Thanks @bobbykellogg I just fixed this!
