### ISSUE TITLE
Submit Your Site: Stock Sandwich

### ISSUE THREAD

**Issue by designedbyross** [ConciseCSS/concisecss.github.io#66]
Hi guys,

We built [Stock Sandwich](https://stocksandwich.com/), a free high-resolution stock photography site, using Concise CSS in October. We've been growing the community ever since and feature great photographers from around the world each month.

Keep up the great work, we love what you're doing with Concise!

Ross Merritt
Little Lightbulb / Stock Sandwich

**Comment by jameskolce** [comment]
Hey @designedbyross 

Awesome! I have added your website. If you build more let me know and I'll be happy to add them, or if you have any problem or question with the framework feel free to [submit an issue](https://github.com/ConciseCSS/concise.css/issues/new).

Thanks for using Concise!

**Comment by designedbyross** [comment]
Thanks @jameskolce that's amazing!
